package com.example.demo1.mapper;

import com.example.demo1.bean.InfoBean;
import com.example.demo1.bean.InfoBean1;
import com.example.demo1.bean.InfoBean2;
import com.example.demo1.bean.InfoBean3;
import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;

public interface InfoMapper {
    List<InfoBean> getAllInfo();
    List<InfoBean> getInfoByYear(Integer year);
    List<InfoBean> getInfoByProvince(String province);
    Integer signIn(String name, String password);
    Integer signUpCheck(String name);
    Integer signUp(String name, String password, String email);
    List<String> getCompanyByProvince(String province);
    List<InfoBean2> getWorkByPandC(@RequestParam("province") String province, @RequestParam("company") String company);
    List<InfoBean3> getAll001();
    List<InfoBean3> getAll002();
    List<InfoBean3> getAll003();
    List<InfoBean3> getAll004();
    List<InfoBean3> getAll005();
    List<InfoBean3> getAll006();
    List<InfoBean3> getAll007();
    List<InfoBean3> getAll008();
    List<InfoBean3> getAll009();
    List<InfoBean3> getAll010();
    List<InfoBean3> getAll011();
    List<InfoBean3> getAll012();
    List<InfoBean3> getAll013();
    List<InfoBean3> getAll014();
    List<InfoBean3> getAll015();
    List<InfoBean3> getAll016();
    List<InfoBean3> getAll017();
    List<InfoBean3> getByYear001(@RequestParam("year") Integer year);
    List<InfoBean3> getByYear002(@RequestParam("year") Integer year);
    List<InfoBean3> getByYear003(@RequestParam("year") Integer year);
    List<InfoBean3> getByYear004(@RequestParam("year") Integer year);
    List<InfoBean3> getByYear005(@RequestParam("year") Integer year);
    List<InfoBean3> getByYear006(@RequestParam("year") Integer year);
    List<InfoBean3> getByYear007(@RequestParam("year") Integer year);
    List<InfoBean3> getByYear008(@RequestParam("year") Integer year);
    List<InfoBean3> getByYear009(@RequestParam("year") Integer year);
    List<InfoBean3> getByYear010(@RequestParam("year") Integer year);
    List<InfoBean3> getByYear011(@RequestParam("year") Integer year);
    List<InfoBean3> getByYear012(@RequestParam("year") Integer year);
    List<InfoBean3> getByYear013(@RequestParam("year") Integer year);
    List<InfoBean3> getByYear014(@RequestParam("year") Integer year);
    List<InfoBean3> getByYear015(@RequestParam("year") Integer year);
    List<InfoBean3> getByYear016(@RequestParam("year") Integer year);
    List<InfoBean3> getByYear017(@RequestParam("year") Integer year);
    List<InfoBean3> getByProvince001(@RequestParam("province") String province);
    List<InfoBean3> getByProvince002(@RequestParam("province") String province);
    List<InfoBean3> getByProvince003(@RequestParam("province") String province);
    List<InfoBean3> getByProvince004(@RequestParam("province") String province);
    List<InfoBean3> getByProvince005(@RequestParam("province") String province);
    List<InfoBean3> getByProvince006(@RequestParam("province") String province);
    List<InfoBean3> getByProvince007(@RequestParam("province") String province);
    List<InfoBean3> getByProvince008(@RequestParam("province") String province);
    List<InfoBean3> getByProvince009(@RequestParam("province") String province);
    List<InfoBean3> getByProvince010(@RequestParam("province") String province);
    List<InfoBean3> getByProvince011(@RequestParam("province") String province);
    List<InfoBean3> getByProvince012(@RequestParam("province") String province);
    List<InfoBean3> getByProvince013(@RequestParam("province") String province);
    List<InfoBean3> getByProvince014(@RequestParam("province") String province);
    List<InfoBean3> getByProvince015(@RequestParam("province") String province);
    List<InfoBean3> getByProvince016(@RequestParam("province") String province);
    List<InfoBean3> getByProvince017(@RequestParam("province") String province);
    String get001(@RequestParam("year") Integer year, @RequestParam("province") String province);
    String get002(@RequestParam("year") Integer year, @RequestParam("province") String province);
    String get003(@RequestParam("year") Integer year, @RequestParam("province") String province);
    String get004(@RequestParam("year") Integer year, @RequestParam("province") String province);
    String get005(@RequestParam("year") Integer year, @RequestParam("province") String province);
    String get006(@RequestParam("year") Integer year, @RequestParam("province") String province);
    String get007(@RequestParam("year") Integer year, @RequestParam("province") String province);
    String get008(@RequestParam("year") Integer year, @RequestParam("province") String province);
    String get009(@RequestParam("year") Integer year, @RequestParam("province") String province);
    String get010(@RequestParam("year") Integer year, @RequestParam("province") String province);
    String get011(@RequestParam("year") Integer year, @RequestParam("province") String province);
    String get012(@RequestParam("year") Integer year, @RequestParam("province") String province);
    String get013(@RequestParam("year") Integer year, @RequestParam("province") String province);
    String get014(@RequestParam("year") Integer year, @RequestParam("province") String province);
    String get015(@RequestParam("year") Integer year, @RequestParam("province") String province);
    String get016(@RequestParam("year") Integer year, @RequestParam("province") String province);
    String get017(@RequestParam("year") Integer year, @RequestParam("province") String province);
}
