server:
  port: 8081

spring:
  datasource:
    name: data
    url: jdbc:mysql://localhost:3306/data
    username: root
    password: fjxsql12345
    driver-class-name: com.mysql.cj.jdbc.Driver

mvc:
  hiddenmethod:
    filter:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo1.bean

logging:
  file:myLog.log
    path:E:/vue/demo1/mylog
